name: causal_inference
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'
      - uses: iterative/setup-cml@v1
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get install libgraphviz-dev
          pip install -r requirements.txt
          python scripts/causal.py
          
          echo "## Random Forest metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Bayesian Network Metrics" > report.md
          cat bn_metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-publish causal_graph.png --md >> report.md
          
          cml-send-comment report.md
